import type { Labels, TextPools } from "../text.js";

/* English strings. Companies, places and people are invented. */

export const pools: TextPools = {
  locale: "en",
  clients: [
    "Quillmere Freight Ltd",
    "Bramblecote Textiles",
    "Orrin Valley Ceramics",
    "Halvard & Pike Supply",
    "Saltmere Cold Storage",
    "Thistlewick Printing",
    "Copperlark Tooling",
    "Wrenfield Agritech",
    "Vellacourt Pharmacy Group",
    "Lumen Hollow Electrics",
    "Pellwick Marine Parts",
    "Greyhaven Joinery",
    "Fennick Office Systems",
    "Marrowby Packaging",
    "Kestrelmoor Logistics",
    "Tallowford Bakeries",
    "Ironbriar Metals",
    "Dunmarrow Glassworks",
    "Cindervale Energy",
    "Oakhallow Furniture",
    "Sablecrest Insurance Brokers",
    "Willowquay Clinics",
    "Glimmerbrook Catering",
    "Hollowfen Builders",
  ],
  regions: [
    "Port Halvard",
    "Wrenmouth",
    "Kestrel Bay",
    "Thornhaven",
    "Amberfield",
    "Saltmere",
    "Greyhollow",
    "Lowmarsh",
  ],
  owners: [
    "Nora Quayle",
    "Felix Ardent",
    "Mina Thorncastle",
    "Owen Bracklow",
    "Lena Pettigrove",
    "Hugo Starling",
    "Ada Wrexford",
    "Silas Penhallow",
    "Iris Coldwater",
    "Jonah Ferriby",
  ],
  authors: [
    "R. Ashcombe",
    "T. Mellor",
    "K. Duvane",
    "S. Brightling",
    "M. Okonji",
    "L. Varga",
    "P. Holloway",
    "E. Strand",
    "J. Kittredge",
    "D. Amberley",
    "C. Rowanby",
    "B. Esterly",
  ],
  comments: [
    "Client asks for a call back after 15:00",
    "Documents under review",
    "Waiting for payment confirmation",
    "Confirm the delivery address",
    "Repeat request, see history",
    "Agreed with the team lead",
    "Loyalty programme discount requested",
    "Urgent, VIP client",
    "Partial refund, statement signed",
  ],
  tags: ["vip", "repeat", "complaint", "instalments", "b2b", "urgent", "documents", "review"],
  colleagueComment: "Colleague's edit {n}",
};

export const labels: Labels = {
  columns: {
    id: "ID",
    client: "Client",
    date: "Date",
    amount: "Amount",
    currency: "Currency",
    status: "Status",
    owner: "Owner",
    region: "Region",
    priority: "Priority",
    sla: "SLA, h",
    tags: "Tags",
    revenue: "Revenue",
    cost: "Cost",
    marginAbs: "Margin",
    marginPct: "Margin %",
    marginPlan: "Margin plan",
    discount: "Discount",
    commission: "Commission",
    tax: "Tax",
    refunds: "Refunds",
    ltv: "LTV",
    conversion: "Conversion %",
    weight: "Weight, kg",
    items: "Items",
    daysOpen: "Days open",
    touches: "Touches",
    comment: "Comment",
    channel: "Channel",
    updatedAt: "Updated",
    createdBy: "Created by",
  },
  status: ["New", "In progress", "Awaiting client", "In review", "Approved", "Rejected", "Closed"],
  priority: ["Low", "Medium", "High"],
  channel: ["Website", "App", "Partner", "Office"],
  presets: { all: "All requests", urgent: "Urgent", finance: "Finance", action: "Needs action" },
};
